### ISSUE TITLE
Is this not suitable in windows 7 environment?

### ISSUE THREAD

**Issue by rinilnath** [PyvesB/javassembly#1]
Hi Pyves!

I am trying some thing very similar to this code, we are working on a legacy migration project.
Cobol to JAVA (we use a tool that help in this) . Some of cobol programs are calling the Assembly programs in its inner level.

So for such Assembly code, the tool we use will not handle and we need a mechanism to call it as it is from Java converted code. 

Please put your thoughts here. 
We need only in windows, because that is the target production environment

**Comment by PyvesB** [comment]
Hello @rinilnath,

It should work on Windows as well, even though I haven't actually tried. The NASM assembler is also distributed on Windows and I would suggest giving MinGW a try rather than Clang/native GCC. Let me know if you manage to get things running! 😉 

Cheers,

Pyves

**Comment by rinilnath** [comment]
Hi There!

I tried with GCC , the .SO file got generated, but on running the Java program.
I am getting the EXCEPTION_ACCESS_VIOLATION. I have attached the log and error screen shot.
[hs_err_pid6632.log](https://github.com/PyvesB/javassembly/files/3600389/hs_err_pid6632.log)
![ErrorFatal](https://user-images.githubusercontent.com/7414473/64691657-ddadd380-d4b0-11e9-82e7-8675079770d9.png)

Have you ever seen this before, please help !

**Comment by PyvesB** [comment]
Interesting. In the build script, did you replace `elf64` by `win64`?

**Comment by rinilnath** [comment]
yes.. i did it . :)
I made another correction in gcc
gcc -shared -o libArraySum.so ArraySum.o

because for my windows -z and -noexecstack was throwing invalid parameters errors
so i removed both. I dont know what it specifically does though

**Comment by PyvesB** [comment]
I'll try to find some time to give a try on my Windows machine over the weekend.

**Comment by rinilnath** [comment]
Thanks Much, please do let me know. I guess the problem is with the file object loading that library arraysum.so,

**Comment by rinilnath** [comment]
I wondered does that .so file shared object is only meant to Linux world and not used in windows.
It needs to be like .dll right ?
Will that gcc can make that object file into the dll library. What you think ?

**Comment by PyvesB** [comment]
~Yes, it probably needs to be a .dll, but I wouldn't expect the GCC command to be much different.~

_Not needed when using MinGW on Windows._

**Comment by rinilnath** [comment]
I tried in DLL , still same error

**Comment by PyvesB** [comment]
Okay, mystery solved! For some reason, I had the idea that calling conventions for registers were architecture-specific. Turns out they're also OS-specific. On Windows, one must follow the conventions as documented [here](https://docs.microsoft.com/cpp/build/x64-software-conventions). In particular:
* arguments are passed in `rcx`, `rdx`, `r8`, `r9` and subsequent ones on the stack rather than `rdi`, `rsi`, `rdx`, `rcx`, `r8`, `r9` and subsequent ones on the stack.
* a four-parameter stack space must be allocated and the stack must be 16-bit aligned before performing a JNI function call.

In others words, when run on Windows, the assembly was trying to perform function calls at pretty much random positions in memory, hence the `EXCEPTION_ACCESS_VIOLATION` errors you were getting.

I've committed a slightly different version of the assembly code alongside a small _.bat_ script, it runs successfully on my Windows machine. Let me know if this makes sense and if the revised Windows code works for you as well!

**Comment by PyvesB** [comment]
Any luck with my help @rinilnath?

**Comment by rinilnath** [comment]
Hi Pyves !

We found that this way is not practical for our requirement, because we eventually have to end up in re writing 18 Assembly programs that was built on COBOL Zos architecture to be compatible Windows just for sake of local testing and then it cannot be put them back into production. 

We proceeded my manually coding the logic in Java and plug off the old Assembly codes

But your tweak i will test it soon and comment the results !
